# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ce7bffca0160e6e0d0c6ffb2060000c28283cad89babc5394d0ce98b32c904a3a2c84b418196ae4000ff1067a740f3636d0e8bc4be9c4fc696af7cfc55cad68c

test:
  secret_key_base: e5fc3e8b06154939abf39393a72e4143abe955d28d471186c21936546814d367174e7771560bad2ebbc4ff664685d61aecd1fe4f7203329c5257730f5d7be6e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
